### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by grikomsn** [grikomsn/rotten-reviews#1]
This packages doesn't verify if the current movie slug exists, so whenever the `movieSlug` parameter doesn't exist or gibberish, this will occur:

```console
$ node bin/rotten-reviews.js wasd 420
(node:10645) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/Users/griko/Projects/Node.js/rotten-reviews/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/griko/Projects/Node.js/rotten-reviews/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/griko/Projects/Node.js/rotten-reviews/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:10645) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async functionwithout a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10645) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Anyone care to implement this? Do submit a PR while it's Hacktoberfest. 🎉

**Comment by 199911** [comment]
Handled in #2
